apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: marciogpc/backend-udg:release
        imagePullPolicy: Always
        resources:
          limits:
            memory: "456Mi"
            cpu: "600m"
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DATABASE_URL
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
