name: Build Backend

on:
  workflow_dispatch:
    inputs:
      build-backend:
        description: 'Build Backend Image and Push to Docker Hub'
        default: 'true'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build backend image
      run: |
        docker build -t kozielgpc/backend-udg:latest ./backend

    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u kozielgpc --password-stdin

    - name: Push image to Docker Hub
      run: |
        docker push kozielgpc/backend-udg:latest
